### ISSUE TITLE
Is Opensea api key necessary now?

### ISSUE THREAD

**Issue by SpacedDot** [nft-api/nft-api#3]
Do I have to have opensea api key to use this api since I have tried, and  it  says access denied.

**Comment by TonyGo888** [comment]
yes, you have to. Since last year i reckoned they're requiring you now. To request for a key go here https://docs.opensea.io/reference/request-an-api-key

**Comment by SpacedDot** [comment]
Thanks for your reply. It's really hard to get one. I request 3 weeks ago, but no responding yet
